version: "3"

services:
  ws:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8001:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SIGN_KEY=${JWT_SIGN_KEY}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - NODE_ENV=${NODE_ENV}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - LOG_LEVEL=${LOG_LEVEL}
